config/routes.rb
Rails.application.routes.draw do
  resources :products

  resources :orders

  resource :cart, only:[:show, :destroy] do
    member do
      post :add, path: 'add/:id'
    end

    collection do
      get :checkout
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart
  attr_reader :items

  def initialize(items = [])
    @items = items
  end

  def add_item(product_id)
    # 檢查是否有重複
    item = items.find { |i| i.product_id == product_id }

    if item
      # 有的話，數量加 1
      item.increment
    else
      # 沒有的話，加入 items
      @items << CartItem.new(product_id)
    end
  end

  def empty?
    items.empty?
  end

  def total_price
    items.reduce(0) { | sum, item| sum + item.total_price }
  end

  def serialize
    result = items.map { |item| {"product_id" => item.product_id,
                                 "quantity" => item.quantity} }
    { "items" => result }
  end

  def self.build_from_hash(hash)
    all_items = []
    if hash && hash["items"]
      all_items = hash["items"].map do |item|
        CartItem.new(item["product_id"], item["quantity"])
      end
    end
    new all_items
  end
end

app/models/cart_item.rb
class CartItem
  attr_reader :product_id, :quantity

  def initialize(product_id, quantity = 1)
    @product_id = product_id
    @quantity = quantity
  end

  def increment(n = 1)
    @quantity += n
  end

  def product
    Product.find_by(id: @product_id)
  end

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items

  validates :name, presence: true
  validates :tel, presence: true
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def init_cart
    @cart = Cart.build_from_hash(session['my_super_cart'])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :find_product, only:[:add]
  before_action :init_cart

  def add
    @cart.add_item(@product.id)
    session['my_super_cart'] = @cart.serialize
    redirect_to products_path, notice: '已放至購物車'
  end

  def show
  end

  def checkout
    @order = Order.new
    @token = Braintree::ClientToken.generate
  end

  private
  def find_product
    @product = Product.find_by(id: params[:id])
    redirect_to products_path if not @product.present?
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :init_cart

  def create
    order = Order.new(order_params)
    @cart.items.each do |item|
      order.order_items.build(product: item.product, quantity: item.quantity)
    end

    if order.save
      # 1. 刷卡
      result = Braintree::Transaction.sale(
        :amount => @cart.total_price,
        :payment_method_nonce => params[:payment_method_nonce],
        :options => {
          :submit_for_settlement => true
        }
      )

      if result
        # 2. 清除購物車
        session['my_super_cart'] = nil
        # 3. 完成後轉往首頁
        redirect_to products_path, notice:'感謝您!!'
      else
        # 失敗處理
      end
    else
      # 失敗處理
    end
  end

  private
  def order_params
    params.require(:order).permit(:name, :tel, :address)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :init_cart

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :price, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/checkout.html.erb
<h2>消費金額 <%= @cart.total_price %></h2>

<%= simple_form_for @order do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :tel %>
  <hr />
  <div id="payment-form"></div>
  <hr />
  <%= f.submit '刷卡!!', class:'btn btn-danger' %>
<% end %>

<script src="https://js.braintreegateway.com/js/braintree-2.30.0.min.js"></script>
<script>
var clientToken = "<%= @token %>";

braintree.setup(clientToken, "dropin", {
  container: "payment-form"
});
</script>

app/views/carts/show.html.erb
<table class="table">
  <tr>
    <td>商品名稱</td>
    <td>數量</td>
    <td>單價</td>
    <td>小計</td>
  <tr/>

  <% @cart.items.each do |item| %>
  <tr>
    <td><%= item.product.title %></td>
    <td><%= item.quantity %></td>
    <td><%= item.product.price %></td>
    <td><%= item.total_price %></td>
  <tr/>
  <% end %>
  <tr>
    <td colspan="3">總計</td>
    <td><%= @cart.total_price %></td>
  </tr>
</table>
<%= link_to '繼續購物', products_path, class:'btn btn-default' %>
<%= link_to '結帳', checkout_cart_path, class:'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HackntuShoppingCart</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.price %></td>
        <td><%= product.description %></td>
        <td><%= link_to '放到購物車', add_cart_path(product), class:'btn btn-danger btn-xs', method: "post" %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="#">賺超大商店</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "購物車(#{@cart.items.count})", cart_path %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>